notify_mobile_app:
  name: Notify via Mobile App
  description: Sends a push notification to all mobile apps corresponding to the given target entities.

  target:
    entity:
      domain: []
    device:
      integration: mobile_app
  
  fields:
    message:
      name: Message
      required: true
      selector:
        text:
    title:
      name: Title
      selector:
        text:
    data:
      name: Data
      selector:
        object:
